# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-03 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienesserviciosmodel',
            name='numero_visita',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
