# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-03 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_servicios', '0002_bienesserviciosmodel_numero_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienesserviciosmodel',
            name='numero_visita',
            field=models.IntegerField(default=0),
        ),
    ]
