# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-16 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auditoriauser'),
        ('bienes_servicios', '0003_auto_20170303_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentariosBienesServiciosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('bienServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes_servicios.bienesServiciosModel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilUsuarioModel')),
            ],
        ),
    ]
